# Generated by Django 4.2.30 on 2026-07-09 00:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('papel_sistema', models.CharField(choices=[('comum', 'Comum'), ('admin', 'Administrador')], default='comum', max_length=10, verbose_name='papel no sistema')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='tipo')),
                ('padrao', models.BooleanField(default=False, verbose_name='padrão')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo inicial')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data')),
                ('fixa', models.BooleanField(default=False, verbose_name='fixa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='core.categoria', verbose_name='categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='core.conta', verbose_name='conta')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.grupo', verbose_name='grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
            ],
            options={
                'verbose_name': 'recomendação',
                'verbose_name_plural': 'recomendações',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor limite')),
                ('periodo', models.DateField(verbose_name='período')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='core.categoria', verbose_name='categoria')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='core.grupo', verbose_name='grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Mesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('periodo_recarga', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=15, verbose_name='período de recarga')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo atual')),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesadas', to=settings.AUTH_USER_MODEL, verbose_name='dependente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesadas', to='core.grupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'mesada',
                'verbose_name_plural': 'mesadas',
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_no_grupo', models.CharField(choices=[('responsavel', 'Responsável'), ('membro', 'Membro'), ('dependente', 'Dependente')], default='membro', max_length=20, verbose_name='papel no grupo')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de entrada')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.grupo', verbose_name='grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro do grupo',
                'verbose_name_plural': 'membros do grupo',
            },
        ),
        migrations.CreateModel(
            name='DivisaoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor devido')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to=settings.AUTH_USER_MODEL, verbose_name='participante')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes', to='core.transacao', verbose_name='transação')),
            ],
            options={
                'verbose_name': 'divisão de despesa',
                'verbose_name_plural': 'divisões de despesas',
            },
        ),
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('recorrencia', models.BooleanField(default=False, verbose_name='recorrência')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_a_pagar', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta a pagar',
                'verbose_name_plural': 'contas a pagar',
            },
        ),
        migrations.CreateModel(
            name='AutorizacaoConsultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('leitura', 'Leitura'), ('comentar', 'Comentar')], default='leitura', max_length=10, verbose_name='nível')),
                ('status', models.BooleanField(default=True, verbose_name='ativa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_como_cliente', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_como_consultor', to=settings.AUTH_USER_MODEL, verbose_name='consultor')),
            ],
            options={
                'verbose_name': 'autorização de consultor',
                'verbose_name_plural': 'autorizações de consultores',
            },
        ),
        migrations.AddConstraint(
            model_name='membrogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'usuario'), name='membro_unico_por_grupo'),
        ),
        migrations.AddConstraint(
            model_name='divisaodespesa',
            constraint=models.UniqueConstraint(fields=('transacao', 'participante'), name='divisao_unica_por_participante'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome'), name='categoria_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='autorizacaoconsultor',
            constraint=models.UniqueConstraint(fields=('consultor', 'cliente'), name='autorizacao_unica_consultor_cliente'),
        ),
    ]
