# Generated by Django 5.2.16 on 2026-07-09 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='MetaEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor alvo')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor atual')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_economia', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'meta de economia',
                'verbose_name_plural': 'metas de economia',
            },
        ),
    ]
