# Generated by Django 5.2.16 on 2026-07-09 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_managers_metaeconomia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesada',
            name='ultima_recarga',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='última recarga'),
        ),
    ]
